### ISSUE TITLE
Update to 1.20.1

### ISSUE THREAD

**Issue by randomsteve95370** [impleri/block-skills#33]
Would be awesome to have this mod updated to 1.20.1. Working on making a custom RPG style pack and this would be perfect for helping Gate Ores behind skills and quests.

**Comment by impleri** [comment]
This will end up with a 1.20 version. I'm currently working on a huge refactor/consolidation in impleri/player-skills#73 first and then I'll get to covering reported bugs and upgrading to 1.20 as well as backporting to 1.18 and 1.16.

**Comment by randomsteve95370** [comment]
Ah very cool. Glad to hear the mod is still being worked on. I think its a highly useful mod for pack devs so I'm glad its still gonna be around.

**Comment by randomsteve95370** [comment]
Ah very cool. Glad to hear the mod is still being worked on. I think its a highly useful mod for pack devs so I'm glad its still gonna be around.
