### ISSUE TITLE
Crash: Cannot read field "idata" because "frame" is null

### ISSUE THREAD

**Issue by TYPyz** [impleri/block-skills#8]
I was experimenting with the features of this mod, and when I finally understood how it works and registered the first 'BlockSkillEvents', the game started crashing with various errors, including the one in the issue title. 
Below you find the crash reports, the mods installed and their versions and the code I wrote.

*Edit:
The game also crashes if i right click on the grass_block

![image](https://user-images.githubusercontent.com/42820115/221903461-4ab4c173-2ed8-406f-8835-acc849da5832.png)
![image](https://user-images.githubusercontent.com/42820115/221903364-abec3a89-6a89-4d05-a264-89da5f6b99fa.png)

![image](https://user-images.githubusercontent.com/42820115/221903940-b4e3e7ff-c016-4a57-b3c8-749f4ee7ee9f.png)

[crash-2023-02-28_16.25.27-client-rightclick on grass.txt](https://github.com/impleri/block-skills/files/10852104/crash-2023-02-28_16.25.27-client-rightclick.on.grass.txt)
[crash-2023-02-28_16.29.12-client-trying to break grass.txt](https://github.com/impleri/block-skills/files/10852106/crash-2023-02-28_16.29.12-client-trying.to.break.grass.txt)
[crash-2023-02-28_16.30.23-client-trying to break grass 2.txt](https://github.com/impleri/block-skills/files/10852107/crash-2023-02-28_16.30.23-client-trying.to.break.grass.2.txt)
[crash-2023-02-28_16.32.30-client-rightclick on grass.txt](https://github.com/impleri/block-skills/files/10852108/crash-2023-02-28_16.32.30-client-rightclick.on.grass.txt)

**Comment by impleri** [comment]
I've caught some of these errors before. I suspect it may have to do with Rhino bridging between JS and Java but I haven't been able to reproduce this deterministically yet to identify the root cause.

**Comment by TYPyz** [comment]
Is there anything I can do to work around this or do I just have to wait for you to fix it? If so, is there anything I can do to help you?

**Comment by impleri** [comment]
After playing around a bit, I think the underlying issue might be easier: memory. In testing restrictions using modids and tags, I noticed crashes similar to this were more frequently. I'm wagering there was some garbage collection going on that was trashing useful data. After upping memory allocation, the errors disappeared.

**Comment by TYPyz** [comment]
I have dedicated 6gb to the testing pack but it keeps crashing on every interaction with the blocks affected by the restrictions, maybe I should try to test by applying the restrictions on a mod and not on minecraft.
[crash-2023-03-02_09.33.01-client.txt](https://github.com/impleri/block-skills/files/10869463/crash-2023-03-02_09.33.01-client.txt)

**Comment by TYPyz** [comment]
I'm trying with other mod id's but every time I interact with any block of that mod the game crashes, by interacting I mean right clicking on a block (even a block that doesn't have a UI) or left clicking on it to break it .

![image](https://user-images.githubusercontent.com/42820115/222487609-7e3c2900-38ab-4ce9-b67c-282382ac5476.png)
[crash-2023-03-02_10.48.00-client.txt](https://github.com/impleri/block-skills/files/10873521/crash-2023-03-02_10.48.00-client.txt)

**Comment by impleri** [comment]
Can you try updating player-skills and block-skills? It's working fine when I target all `rechiseled` blocks ([source](https://github.com/impleri/test-skills/blob/main/server/blocks.js#L7))

**Comment by TYPyz** [comment]
I've checked if all the mods were up to date and tested it again restricting all blocks from ae2 and it keeps crashing, this time the crash error is different `Java method "cannot" was invoked with null as "this" value that can not be converted to Java type net.impleri.playerskills.restrictions.PlayerDataJS. (startup_scripts:skills_startup.js#11)`
![image](https://user-images.githubusercontent.com/42820115/223079650-7d2f95da-b051-4b37-8cfe-492153b70d35.png)
![image](https://user-images.githubusercontent.com/42820115/223079730-896bbbc9-2c30-484e-a431-f2ee0c24212f.png)
[crash-2023-03-06_10.59.28-client.txt](https://github.com/impleri/block-skills/files/10896789/crash-2023-03-06_10.59.28-client.txt)

**Comment by impleri** [comment]
I'm starting to suspect impleri/player-skills#34 may be the root cause.

**Comment by impleri** [comment]
I'm getting this a lot less often now, so I assume it may have been performance-related. @TYPyz can you confirm that the recent updates resolved this?

**Comment by TheYoloPanda** [comment]
I apologize for the late response. Today, I finally had the time to test this bug again, and I confirm that it has been fixed, and the game no longer crashes.😁🥳
